version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gorm.io/gorm
    versions:
    - 1.21.5
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.23.0
    - 5.24.0
    - 5.24.4
    - 5.25.0
    - 5.26.2
    - 5.26.3
    - 5.27.0
    - 5.30.0
    - 5.31.0
    - 5.32.0
    - 5.33.2
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: ts-loader
    versions:
    - 8.2.0
    - 9.0.2
    - 9.1.0
  - dependency-name: postcss
    versions:
    - 8.2.12
    - 8.2.8
    - 8.2.9
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.4.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.8
    - 1.3.9
    - 1.5.0
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: tailwindcss
    versions:
    - 2.1.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.1
    - 4.18.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.2
    - 4.20.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: postcss-loader
    versions:
    - 5.2.0
  - dependency-name: html-webpack-plugin
    versions:
    - 5.3.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  registries:
  - npm-registry-npm-pkg-github-com
