root = "."
tmp_dir = "tmp"


[build]
cmd = "go build -o spin ./cmd/app/main.go"
bin = "spin"
include_ext = ["go", "tpl", "tmpl", "html", "ts", "tsx", "js"]
exclude_dir = ["tmp", "vendor", "node_modules"]
log = "air.log"
delay = 1000