version: '3.8'
services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
    command: air -c .air.toml
    ports:
      - "1323:1323"
    environment:
      TWITTER_API_KEY: ${TWITTER_API_KEY}
      TWITTER_API_KEY_SECRET: ${TWITTER_API_KEY_SECRET}
      CALLBACK_URL: ${CALLBACK_URL}
      DATABASE_URL: ${DATABASE_URL}
    links:
      - db
  db:
    image: postgres:13.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: spin
      POSTGRES_PASSWORD: spin
      POSTGRES_DB: spin
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
