version: '3.8'
services:
  app:
    build:
      context: .
      target: dev
    env_file:
      - ./.env
    volumes:
      - ./:/app
    command: air -c .air.toml
    ports:
      - "1323:1323"
    links:
      - db
  db:
    image: postgres:13.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: spin
      POSTGRES_PASSWORD: spin
      POSTGRES_DB: spin
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
