CREATE TABLE IF NOT EXISTS users(
  id serial PRIMARY KEY,
  name VARCHAR (50) UNIQUE NOT NULL,
  twitter_account_id text UNIQUE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
